server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:leadsdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

# Swagger UI path (optional)
springdoc:
  swagger-ui:
    path: /swagger-ui.html
